import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { GlobalState } from "@/global/global-state";
import { ModalProvider } from "@/global/modal-provider";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IETLS Simulation",
  description: "Generated by",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const headersList = headers();
  const pathname = headersList.get("x-invoke-path") || "";
  const showHeaderFooter = pathname !== "/" && !pathname?.startsWith('/mock-tests/');
  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GlobalState>
              <ModalProvider />
              <div className="relative flex min-h-screen flex-col">
                {showHeaderFooter && <SiteHeader user={session?.user} />}
                <main className="flex-1">
                  {children}
                </main>
                {showHeaderFooter && <SiteFooter />}
              </div>
            </GlobalState>
            <Toaster closeButton />
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
